.ALTER SNFP
.lib '/home/caleixo/NGSpiceLibraries/L130E_HGIO_LVT33_V131/L130E_HG_LVT33_V131.lib.ngspice' SNFP

.ALTER FNSP
.lib '/home/caleixo/NGSpiceLibraries/L130E_HGIO_LVT33_V131/L130E_HG_LVT33_V131.lib.ngspice' FNSP

.ALTER FF
.lib '/home/caleixo/NGSpiceLibraries/L130E_HGIO_LVT33_V131/L130E_HG_LVT33_V131.lib.ngspice' FF

.ALTER VMAX
.PARAM
+_vdd=3.63

.ALTER VMIN
.PARAM
+_vdd=2.97

.ALTER TMAX
.TEMP 55.0

.ALTER TMIN
.TEMP 0


