.ALTER SNFP
.lib '/Users/Catarina/Desktop/Tese/Libraries/L130E_HGIO_LVT33_V131/L130E_HG_LVT33_V131.lib.eldo' SNFP

.ALTER FNSP
.lib '/Users/Catarina/Desktop/Tese/Libraries/L130E_HGIO_LVT33_V131/L130E_HG_LVT33_V131.lib.eldo' FNSP

.ALTER FF
.lib '/Users/Catarina/Desktop/Tese/Libraries/L130E_HGIO_LVT33_V131/L130E_HG_LVT33_V131.lib.eldo' FF

.ALTER VMAX
.PARAM
+_vdd=3.63

.ALTER VMIN
.PARAM
+_vdd=2.97

.ALTER TMAX
.TEMP 55.0

.ALTER TMIN
.TEMP 0


